biojppm/rapidyaml

- src/c4/yml/common.hpp
This replaces RYML_USE_ASSERT with C4_USE_ASSERT since there is no easy
way to rename the preprocessor macro. Currently, if RYML_USE_ASSERT is
not defined, then RYML_USE_ASSERT is always defined, which means that
asserts are always enabled (regardless of whether C4_USE_ASSERT is
defined or not).
> common: Fix USE_ASSERT check

- .ci/travis-setenv.sh
- .gitignore
- CHANGELOG.md
- src/c4/yml/common.cpp
- src/c4/yml/common.hpp
- src/c4/yml/detail/parser_dbg.hpp
- src/c4/yml/parse.cpp
- src/c4/yml/parse.hpp
- test/CMakeLists.txt
- test/double_quoted.cpp
- test/github_issues.cpp
- test/libyaml.hpp
- test/parse_emit.cpp
- test/plain_scalar.cpp
- test/simple_doc.cpp
- test/single_quoted.cpp
- test/test_case.cpp
- test/test_case.hpp
- test/test_group.cpp
> Improve parsing of plain (unquoted) scalars

- src/c4/yml/detail/parser_dbg.hpp
- src/c4/yml/preprocess.cpp
- test/preprocess.cpp
> re #52: fixes fail on json preprocessing

- CHANGELOG.md
- src/c4/yml/emit.def.hpp
- src/c4/yml/parse.cpp
- src/c4/yml/parse.hpp
- src/c4/yml/tree.cpp
- test/test_case.cpp
- test/test_case.hpp
- test/test_github_issues.cpp
- test/test_null_val.cpp
- test/test_seq_of_map.cpp
- test/test_simple_map.cpp
- test/test_simple_set.cpp
- test/test_tag_property.cpp
***Breaking change***: null values in YAML are now parsed to null strings instead of YAML null token `"~"`:
```c++
auto tree = parse("{foo: , bar: ''}");
// previous:
assert(tree["foo"].val() == "~");
assert(tree["bar"].val() == "");
// now:
assert(tree["foo"].val() == nullptr); // notice that this is now null
assert(tree["bar"].val() == "");
```
Fixes [#84](https://github.com/biojppm/rapidyaml/issues/84).
> [break] use null strings when parsing YAML-null values

- .github/workflows/ci.yml
See https://github.com/biojppm/rapidyaml/actions/runs/481510848, which is still reporting a syntax error.
> Fix GH Actions YAML file.

- CMakeLists.txt
- cmake/uninstall.cmake
Hello,
Thanks for the nice lib! This PR adds an uninstall target to CMake.
> Add uninstall target

- src/c4/yml/parse.cpp
- test/test_basic.cpp
As discussed in #124, the parser gets confused on the following input:
```yaml
a:
- b
c: d
```
This PR adds a test case for this input and also contains a fix.
> Fix parse failure in comments ending with colon (#124)

- changelog/current.md
- src/c4/yml/node.hpp
- src/c4/yml/parse.cpp
- src/c4/yml/tree.cpp
- src/c4/yml/tree.hpp
- test/test_basic.cpp
- test/test_suite/test_suite_events.cpp
* remove all predicates from `NodeData`
* forward `Tree` type predicates to `NodeType` predicates
* forward `NodeRef` type predicates to `NodeType` predicates
* ensure test coverage of all type predicates
fixes #154
> [fix] ensure type predicate consistency

- .gitignore
- src/c4/yml/parse.cpp
- src/c4/yml/parse.hpp
- test/test_block_folded.cpp
> [fix] parse error with multi-line scalars that are the last in a sequence

- changelog/current.md
- src/c4/yml/emit.def.hpp
- src/c4/yml/emit.hpp
- src/c4/yml/node.hpp
- src/c4/yml/parse.cpp
- src/c4/yml/parse.hpp
- src/c4/yml/tree.cpp
- src/c4/yml/tree.hpp
- test/test_double_quoted.cpp
- test/test_plain_scalar.cpp
- test/test_simple_anchor.cpp
- test/test_simple_doc.cpp
- test/test_single_quoted.cpp
> [fix] ensure ref-looking scalars are quoted

- api/python/Makefile
- api/python/ryml/tests/test_parse.py
- api/ryml.i
This PR adds node predicates `is_anchor_or_ref()`, `is_quoted()`, `is_key_quoted()` and `is_val_quoted()` to the SWIG API definition for both `struct Tree` and `struct NodeType`.
Additionally, the PR changes the `SimpleHardCoded` Python API test case to have a quoted key and value respectively and adds assertions for the quoting-related predicates.
Fixes #165
> Add missing node predicates in the Python API

- .github/reqs.sh
error was:
```
+ cpack -G ZIP
Chocolatey v0.11.3
File specified is either not found or not a .nuspec file. 'ZIP'
```
> [fix] github actions: remove choco executable overriding CMake's CPack

- tools/amalgamate.py
When using amalgamate.py to generate head files, `--no-c4core` can cause error:
```
Traceback (most recent call last):
File "tools/amalgamate.py", line 126, in <module>
amalgamate_ryml(filename=args.output,
File "tools/amalgamate.py", line 75, in amalgamate_ryml
am.onlyif(with_c4core, c4core_amalgamated),
UnboundLocalError: local variable 'c4core_amalgamated' referenced before assignment
```
So `c4core_amalgamated` needs to be defined even if `with_c4core` is false. Here I defined it as a empty string.
> fix possible error: local variable 'c4core_amalgamated' referenced before assignment.

- samples/quickstart.cpp
In `quickstart.cpp`, due to line 1749, the sample wants to show how to use `<<` to avoid lifetime dependency. Thus, a `std::string a_drop` is defined, but after this `a_drop` is not really used.
> modify sample_create_trees()

- README.md
> If you omit --recursive, after cloning you will have to do git submodule init and git submodule update to ensure ryml's submodules are checked out.
With git version `2.25.1` the proposed doc does not add submodules from the `c4core` library:
```bash
$ git clone https://github.com/biojppm/rapidyaml.git
$ cd rapidyaml
$ git submodule init
Submodule 'extern/c4core' (https://github.com/biojppm/c4core) registered for path 'ext/c4core'
$ git submodule update
Cloning into '/tmp/zzz/rapidyaml/ext/c4core'...
Submodule path 'ext/c4core': checked out 'e4c1554283cdc1a22a358b59df4e30b5e2edebe6'
```
This command adds submodules from the c4core lib:
```bash
$ git submodule update --init --recursive
...
Submodule path 'ext/c4core': checked out 'e4c1554283cdc1a22a358b59df4e30b5e2edebe6'
...
Submodule …
```
> [doc] fix git submodule recursive command

- README.md
- samples/singleheader/amalgamate.cmake
In Ubuntu 20.04 the default `python` [command](https://github.com/biojppm/rapidyaml/blob/master/samples/singleheader/amalgamate.cmake#L12-L13) is associated with python 2.7.X. This PR changes the amalgamate tool command to use `python3` because of the incompability with python2.
Alternatives:
- Change `f-Strings` to `str.format()` ... 
- Add `#!/usr/bin/env python3` in file and call without python command (also make script executable). Would be best for portability ? E.g I suspect python and python3 commands to not work in windows...
I can remove the change in the doc if you want.
> [fix] specify python3 command for the amalgamate tool

- changelog/current.md
- src/c4/yml/emit.def.hpp
- test/test_double_quoted.cpp
> double-quoted emitter should escape carriage return to ensure roundtrip equivalence

- changelog/current.md
- src/c4/yml/tree.cpp
- src/c4/yml/tree.hpp
- test/test_case.cpp
- test/test_tree.cpp
> [fix] Tree::_grow_arena() should start from size and not position

- changelog/current.md
- src/c4/yml/parse.cpp
- test/test_simple_map.cpp
> [fix] re #274 indentless seqs with trailing empty values

- changelog/0.5.0.md
- src/c4/yml/emit.def.hpp
- test/test_json.cpp
> [fix] json emitter should escape control characters

- test/test_case.cpp
- test/test_case.hpp
- test/test_group.cpp
- test/test_group.hpp
- test/test_number.cpp
- test/test_parser.cpp
See https://github.com/google/jsonnet/issues/1014
> Adds a unit test to parse 3 digits versions

- README.md
- changelog/0.5.0.md
- samples/quickstart.cpp
- src/c4/yml/emit.def.hpp
- src/c4/yml/emit.hpp
- test/test_basic.cpp
- test/test_block_literal.cpp
- test/test_case.hpp
- test/test_double_quoted.cpp
- test/test_emit.cpp
- test/test_group.cpp
- test/test_group.hpp
- test/test_json.cpp
- test/test_merge.cpp
- test/test_noderef.cpp
- test/test_number.cpp
- test/test_seq_of_map.cpp
- test/test_serialize.cpp
- test/test_simple_anchor.cpp
- test/test_simple_doc.cpp
- test/test_simple_set.cpp
- test/test_style.cpp
- test/test_suite.cpp
- test/test_tag_property.cpp
- test/test_tree.cpp
- tools/parse_emit.cpp
> [refac] deprecate emit() and emitrs(), use emit_yaml() and emitrs_yaml()

- changelog/0.5.0.md
- samples/quickstart.cpp
- src/c4/yml/parse.cpp
- src/c4/yml/parse.hpp
- test/test_case.cpp
- test/test_case.hpp
- test/test_location.cpp
> [fix breaking] locations require opt-in when creating the parser

- src/c4/yml/emit.def.hpp
- test/test_json.cpp
> [fix] do not add quotes to 0-leading float numbers

- changelog/0.5.0.md
- src/c4/yml/parse.cpp
> [fix] eager scan for carriage return caused slow parsing

- changelog/0.5.0.md
- src/c4/yml/tree.cpp
- src/c4/yml/tree.hpp
- test/test_github_issues.cpp
don't call move with prev = NONE
Fixes #277
> fix Tree::duplicate_children_no_rep

- setup.py
The dependency on the PyPI [deprecation](https://pypi.org/project/deprecation/) package already appears in requirements.txt,
https://github.com/biojppm/rapidyaml/blob/b35ccb150282760cf5c2d316895cb86bd161ac89/requirements.txt#L8
but it is not only a build-time dependency. The import in `api/ryml.i`
https://github.com/biojppm/rapidyaml/blob/b35ccb150282760cf5c2d316895cb86bd161ac89/api/ryml.i#L218
ends up in the generated `ryml/ryml.py`, so we need to add a runtime dependency. This commit adds the necessary dependency via a new `install_requires` argument in `setup.py`.
Fixes:
```
==================================== ERRORS ====================================
_______________ ERROR collecting api/python/tests/test_parse.py ________________
ImportError while importing test module …
```
> [fix] Add missing Python runtime dep. on deprecation

- changelog/current.md
- src/c4/yml/parse.cpp
- test/test_simple_map.cpp
> [fix] re #361: fix parse of scalars with : and starting on the next line

- src/c4/yml/node.hpp
Marking a function as pure implies that it does not have any observable side effects (only the return value is used). So if the compiler detects that the return value of a pure function is not used, it may eliminate the call to the pure function.
This would be wrong, however, if the passed in Visitor has side effects which are needed by the program.
Fix this by not marking the visit functions as pure.
> Do not mark visit functions as pure

- .github/workflows/release.yml
Really not sure that it's the only thing I need to do to support Python 3.12 😛 
Fixes https://github.com/biojppm/rapidyaml/issues/391
> chore: Add support for Python 3.12

- pyproject.toml
https://github.com/Farama-Foundation/Gymnasium/issues/245#issuecomment-1377986714
> fix: Add swig as build dependency

- src/c4/yml/parse.cpp
> Use _c4err macro for error message 'closing ] not found'

- src/c4/yml/detail/stack.hpp
- src/c4/yml/tree.hpp
I have replaced `noexcept` for a few places with macro but not the ones that are move constructor.
All the ones I replaces have asserts which can throw (I think)
For #411
> Replacing noexcept to RYML_NOEXCEPT for stack and tree

- samples/quickstart.cpp
> Add quickstart example addressing float precision and avoiding loss.

- CMakeLists.txt
- README.md
- changelog/current.md
- samples/quickstart.cpp
- src/c4/yml/common.cpp
- src/c4/yml/common.hpp
- src/c4/yml/detail/stack.hpp
- src/c4/yml/emit.def.hpp
- src/c4/yml/emit.hpp
- src/c4/yml/node.hpp
- src/c4/yml/parse.cpp
- src/c4/yml/parse.hpp
- src/c4/yml/std/vector.hpp
- src/c4/yml/tree.cpp
- src/c4/yml/tree.hpp
- test/callbacks_tester.hpp
- test/test_case.cpp
- test/test_case.hpp
- test/test_github_issues.cpp
- test/test_group.hpp
- test/test_noderef.cpp
- test/test_tree.cpp
Fixes #389 
Fixes #362
Fix major error handling problem reported in [#389](https://github.com/biojppm/rapidyaml/issues/389) ([PR#411](https://github.com/biojppm/rapidyaml/pull/411)):
- The `NodeRef` and `ConstNodeRef` classes had many methods marked `noexcept` that were doing assertions which could throw exceptions, causing an abort instead of a throw whenever the assertion called an exception-throwing error callback.
- Also, this problem was compounded by exceptions being enabled in every build type -- despite the intention to have them only in debug builds. There was a problem in the preprocessor code to enable assertions which led to assertions being enabled in release builds even when `RYML_USE_ASSERT` was defined to 0. Thanks to @jdrouhard for reporting this.
- Although the code is …
> Improve error handling

- .github/release.sh
- .github/reqs.sh
- .github/setenv.sh
- .github/workflows/clang.yml
- .github/workflows/clang_tidy.yml
- .github/workflows/coverage.yml
- .github/workflows/gcc.yml
- .github/workflows/install.yml
- CMakeLists.txt
- bm/CMakeLists.txt
- doc/sphinx_other_languages.rst
- samples/quickstart.cpp
- src/c4/yml/common.hpp
- src/c4/yml/detail/parser_dbg.hpp
- test/CMakeLists.txt
- test/test_callbacks.cpp
- test/test_case.cpp
- test/test_number.cpp
- test/test_suite/test_suite_events.cpp
- test/test_suite/test_suite_events_emitter.cpp
- tools/yaml_events.cpp
use longjmp() when exceptions are disabled
Fixes #359
> [fix] ensure tests run with disabled exceptions

- src/ryml.natvis
I set up the natvis in a new project that is using rapidyml and it was missing the primary type that we are using (`ConstNodeRef`).  Additionally I discovered that the children synthetic visualization for NodeRef/ConstNodeRef was not being parsed correctly.  The order of operations on the bitwise operator was causing the condition to always evaluate to false.
* Duplicate the `NodeRef` visualization as `ConstNodeRef`.  ConstNodeRef does not have an m_seed field so it cannot be exactly identical or else it fails to apply.
* Tweak `NodeData::m_parent` to special-case `NONE` instead of printing uint64(-1).
* Fix the [children] expansion in NodeRef/ConstNodeRef.
* Expand `elm` to `element`.  (This one is arguable; I'm tempted to expand them all out so they are easier to understand without …
> Update natvis to include a few tweaks

- changelog/current.md
- samples/quickstart.cpp
- src/c4/yml/common.hpp
- src/c4/yml/node.hpp
- test/test_serialize.cpp
> ensure empty values are not deserialized

- changelog/current.md
- samples/quickstart.cpp
- src/c4/yml/node.hpp
- src/c4/yml/node_type.cpp
- src/c4/yml/tree.hpp
- test/test_node_type.cpp
- test/test_serialize.cpp
> numbers: fix serialization with `+`, fix emit style heuristics

- .github/workflows/gcc.yml
- changelog/current.md
- src/c4/yml/event_handler_tree.hpp
- src/c4/yml/parse.cpp
- src/c4/yml/parse_engine.def.hpp
- src/c4/yml/parser_state.hpp
- src/c4/yml/reference_resolver.cpp
- test/test_noderef.cpp
- test/test_serialize.cpp
- test/test_tree.cpp
> Fix test failures with gcc -O2

- src/c4/yml/parse_engine.def.hpp
This PR fixes an issue where the single-quote parser was incorrectly specified for double-quoted keys in YAML map blocks.
> fix: correct parser for double-quoted keys in map block

- changelog/current.md
- src/c4/yml/std/map.hpp
- src/c4/yml/std/vector.hpp
- test/test_serialize.cpp
> read<std::map>() implementation: overwrite existing entries

- changelog/current.md
- src/c4/yml/parse_engine.def.hpp
- test/test_github_issues.cpp
- test/test_lib/test_case.cpp
> block containers: fix parsing of trailing whitespace

- changelog/current.md
- src/c4/yml/node.hpp
- src/c4/yml/reference_resolver.cpp
- src/c4/yml/reference_resolver.hpp
- src/c4/yml/tree.cpp
- src/c4/yml/tree.hpp
- test/test_anchor.cpp
- test/test_merge.cpp
- test/test_tree.cpp
- tools/parse_emit.cpp
> Fix merge key order, clear anchors after resolving

- src/c4/yml/common.hpp
This PR resolves the deprecation warning triggered by the use of `std::is_trivial<LineCol>` in RapidYAML headers when building on C++26 standard.
---
During build, the following warning was emitted:
```
/bin/_deps/rapidyaml-src/src/c4/yml/common.hpp:291:20: warning: 'is_trivial[c4::yml::LineCol]' is deprecated:
Consider using is_trivially_copyable<T>::value && is_trivially_default_constructible<T>::value instead [-Wdeprecated-declarations]
```
On line:
`static_assert(std::is_trivial<LineCol>::value, "LineCol not trivial");`
---
- No functional changes to RapidYAML.  
- Build output is now clean on all supported platforms/compilers.  
- Future-proof against deprecated traits warnings in C++26, but still complies with C++11.
> Swap std::is_trivial with non deprecated traits

- README.md
- samples/quickstart.cpp
- src/c4/yml/parse_engine.def.hpp
- test/test_scalar_dquoted.cpp
This part was unescaping `\xXX` incorrectly (it was just dumping the codepoint as a byte.)
> Fix \x codepoint parsing, was not decoded
