biojppm/rapidyaml

CMakeLists.txt, api/CMakeLists.txt, api/python/parse.py, api/ryml.i, ryml.natvis, src/c4/yml/detail/checks.hpp, src/c4/yml/detail/print.hpp, src/c4/yml/emit.def.hpp, src/c4/yml/emit.hpp, src/c4/yml/parse.cpp, src/c4/yml/tree.cpp, src/c4/yml/tree.hpp, src/c4/yml/writer.hpp, test/CMakeLists.txt, test/basic.cpp, test/simple_anchor.cpp, test/test_case.cpp, test/test_case.hpp, test/test_group.cpp, test/test_group.hpp
* implement alias sequences
* add tree reorder()
* tidy emit api
* fix swig tests
=> merge from dev:

ryml.natvis, src/c4/yml/emit.hpp, src/c4/yml/tree.cpp, src/c4/yml/tree.hpp, test/CMakeLists.txt, test/basic.cpp, test/libyaml.hpp, test/merge.cpp, test/suite.cpp, test/test_case.hpp
- add merge API
- split reserve() and reserve_arena()
- update cmake infrastructure
- general fixes
=> merge dev branch

.gitignore, src/c4/yml/common.cpp, src/c4/yml/parse.cpp, test/github_issues.cpp
=> Fixes #54: whitespace before semicolon

CMakeLists.txt, README.md, appveyor.yml, bm/CMakeLists.txt, bm/bm_parse.cpp, src/c4/yml/common.hpp, src/c4/yml/detail/checks.hpp, src/c4/yml/detail/stack.hpp, src/c4/yml/node.hpp, src/c4/yml/parse.cpp, src/c4/yml/parse.hpp, src/c4/yml/preprocess.cpp, src/c4/yml/tree.cpp, src/c4/yml/tree.hpp, src/c4/yml/writer.hpp, test/libyaml.hpp, test/parse_emit.cpp, test/test_basic.cpp, test/test_case.cpp, test/test_case.hpp, test/test_empty_file.cpp, test/test_group.cpp, test/test_indentation.cpp, test/test_null_val.cpp, test/test_simple_set.cpp, test/test_stack.cpp
=> fixes #80: extra pedantic warnings

.github/workflows/create_c4_pack.yml, CMakeLists.txt, README.md, test/parse_emit.cpp, test/test_basic.cpp
fixes #74 : deserialization of boolean strings
fixes #75 : cannot compile or install on MacOS
=> [chore] update c4core

README.md, src/c4/yml/emit.hpp
=> use fast_float to read real numbers, fixes quadratic performance from sscanf

.github/workflows/ci.yml, src/c4/yml/parse.cpp, test/test_case.hpp, test/test_group.cpp, test/test_null_val.cpp
=> null should not be read as string

src/c4/yml/tree.cpp, test/test_case.cpp, test/test_github_issues.cpp, test/test_group.cpp
Fix for #128, including two small test cases.
=> Fix segfault when accessing nonexistent anchor (#128)

.github/reqs.sh, README.md, bm/CMakeLists.txt, test/CMakeLists.txt, test/test_basic.cpp, test/test_case.cpp, test/test_null_val.cpp, test/test_simple_anchor.cpp
=> Post gtest upgrade fix

src/c4/yml/emit.def.hpp, src/c4/yml/emit.hpp, src/c4/yml/parse.cpp, src/c4/yml/parse.hpp, src/c4/yml/tree.hpp, test/test_case.cpp
=> [tidy] re #132: post merge adjustments

src/c4/yml/emit.def.hpp, src/c4/yml/emit.hpp, src/ryml.natvis, test/test_basic_json.cpp
=> Preserve quotes when emitting scalars

changelog/current.md, samples/quickstart.cpp, src/c4/yml/node.hpp, src/c4/yml/tree.hpp, test/test_basic.cpp
=> fix serialization of special float values nan, inf

changelog/current.md, samples/add_subdirectory/CMakeLists.txt, samples/add_subdirectory/run.sh, samples/custom_c4core/CMakeLists.txt, samples/custom_c4core/run.sh, samples/fetch_content/CMakeLists.txt, samples/fetch_content/run.sh, samples/find_package/run.sh
=> [fix] re #173: add alias target ryml::ryml

.github/setenv.sh, .github/workflows/emscripten.yml, README.md, changelog/current.md, samples/quickstart.cpp
=> [impl] add support for compilation from emscripten

.github/workflows/test.yml, changelog/current.md, samples/quickstart.cpp, samples/singleheader/CMakeLists.txt, samples/singleheaderlib/CMakeLists.txt, samples/singleheaderlib/lib.cpp, samples/singleheaderlib/run_shared.sh, samples/singleheaderlib/run_static.sh, src/c4/yml/preprocess.hpp, tools/amalgamate.py
=> [wip] fix exports in single header

changelog/current.md, src/c4/yml/parse.cpp, src/c4/yml/tree.hpp, test/test_basic.cpp, test/test_basic_json.cpp, test/test_callbacks.cpp, test/test_case.cpp, test/test_group.cpp, test/test_merge.cpp, test/test_null_val.cpp, test/test_preprocess.cpp, test/test_singleheader/CMakeLists.txt, test/test_stack.cpp, test/test_suite.cpp, test/test_suite/test_suite_common.hpp, test/test_suite/test_suite_events.cpp, test/test_suite/test_suite_events.hpp, test/test_suite/test_suite_parts.hpp, tools/amalgamate.py
=> [fix] accept mixed and upper case null, .inf, .nan

.github/workflows/macosx.yml, .github/workflows/test.yml, changelog/current.md
=> fix compilation fail in xcode 12.0

.github/workflows/clang.yml, .github/workflows/clang_tidy.yml, changelog/current.md, src/c4/yml/parse.cpp, test/test_simple_map.cpp
=> fix assertion peeking scalar on last line when it is whitespace only

changelog/current.md, src/c4/yml/parse.cpp, src/c4/yml/tree.hpp, test/test_simple_map.cpp
=> Parser: accept leading colon in UNK node

src/c4/yml/std/vector.hpp, test/test_serialize.cpp
=> fix deserialization of std::vector<bool>

changelog/current.md, src/c4/yml/node.hpp, test/test_noderef.cpp
=> NodeRef: const overloads did not participate in overload resolution

changelog/0.5.0.md, samples/quickstart.cpp, src/c4/yml/emit.def.hpp, test/test_json.cpp
=> json emitter: fixes to scalars with missing quotes

.github/setenv.sh, .github/workflows/coverage.yml, test/test_json.cpp
see lemurheavy/coveralls-public#1665
=> [ci] disable coveralls parallel submission

changelog/0.5.0.md, src/c4/yml/emit.def.hpp, test/test_emit.cpp
=> [fix] emitted scalars containing @ should be quoted

changelog/0.5.0.md, src/c4/yml/node.hpp, src/c4/yml/tree.cpp, test/test_noderef.cpp
=> [fix] eager assertions prevented moving nodes to the first position

changelog/0.5.0.md, src/c4/yml/tree.cpp, src/c4/yml/tree.hpp, test/test_case.cpp, test/test_noderef.cpp
=> improve complexity of has_sibling() and has_child()

changelog/0.5.0.md, src/c4/yml/tree.hpp, test/test_github_issues.cpp
~~A test case like in #268 should be added, too.~~ Done
Fixes #268
=> Don't override key type_bits when copying val

README.md
Feel free to reformat or rephrase this if you like.
See also https://src.fedoraproject.org/rpms/rapidyaml.
=> [doc] Add Fedora Linux and EPEL packages to README.md

changelog/current.md, samples/quickstart.cpp, src/c4/yml/common.cpp, src/c4/yml/common.hpp, src/c4/yml/detail/print.hpp, src/c4/yml/detail/stack.hpp, src/c4/yml/node.hpp, src/c4/yml/parse.cpp, src/c4/yml/preprocess.cpp, src/c4/yml/tree.cpp, src/c4/yml/tree.hpp, test/callbacks_tester.hpp, test/test_case.cpp, test/test_case.hpp, test/test_parser.cpp, test/test_stack.cpp, test/test_suite/test_suite_events.cpp, test/test_suite/test_suite_events_emitter.cpp, tools/parse_emit.cpp, tools/yaml_events.cpp
=> [fix] pedantic compiler warnings

bm/bm_common.hpp, changelog/current.md, src/c4/yml/parse.cpp, test/test_json.cpp, test/test_plain_scalar.cpp, test/test_simple_map.cpp, test/test_suite/test_suite_common.hpp, test/test_tree.cpp
=> [fix] re #373: fix parsing of empty keys in block-style maps

changelog/current.md, test/test_json.cpp
=> fix emitting of scientific number with one exponent digit

src/c4/yml/common.hpp
Please refer c4core issue.
https://github.com/biojppm/c4core/pull/139
=> Plase use malloc.h instead of alloca.h on MinGW

changelog/current.md, src/c4/yml/parse_engine.def.hpp, test/test_github_issues.cpp
=> fix parsing of val-less nested maps when deindented to maps

.github/toolchains/linux-gnu-powerpc64le.cmake, changelog/current.md, src/c4/yml/parse_engine.def.hpp
=> Workaround for failures with ppc64le g++14 -O2

changelog/current.md, src/c4/yml/event_handler_tree.hpp, test/test_suite/test_suite_common.hpp
=> fixes warnings with -Wundef

.github/reqs.sh, .github/setenv.sh, .github/workflows-in/clang.ys, .github/workflows-in/install.ys, .github/workflows-in/release.ys, .github/workflows-in/samples.ys, .github/workflows/install.yml, .github/workflows/release.yml, .github/workflows/samples.yml, bm/CMakeLists.txt, changelog/current.md
=> fix build with cmake 4

.github/workflows-in/Makefile, .github/workflows-in/release.ys, .github/workflows/release.yml, README.md, api/python/tests/test_readme.py, doc/sphinx_other_languages.rst
=> fix python README example, run as test

changelog/current.md, src/c4/yml/parse_engine.def.hpp, test/test_parse_engine_6_qmrk.cpp
Fix #524
Thanks @MatthewSteel!
=> Fix #524: parse of complex map

changelog/current.md, samples/quickstart.cpp, src/c4/yml/node.hpp, src/c4/yml/node_type.hpp, src/c4/yml/tree.cpp, src/c4/yml/tree.hpp
=> Style improvements
